version: '2'
services:
  icounseling-app:
    image: icounseling
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=***
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATASOURCE_USERNAME=***
      - SPRING_DATASOURCE_PASSWORD=***
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  icounseling-mysql:
    extends:
      file: mysql.yml
      service: icounseling-mysql
