version: '2'
services:
  icounseling-mysql:
    image: mysql:8.0.16
    # volumes:
    #     - ~/volumes/jhipster/iCounseling/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=icounseling
      - MYSQL_PASSWORD=1245783690
      - MYSQL_DATABASE=icounseling
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
