version: '2'
services:
  icounseling-mysql:
    image: mysql:8.0.16
    # volumes:
    #     - ~/volumes/jhipster/iCounseling/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=***
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_DATABASE=***
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
